In [11]:
import numpy as np
x = np.array(([1,2],[3,4]), dtype = np.float)
y = np.array(([5,6],[7,8]), dtype = np.float)

print(x)
print()

print(y)
print()

print(x + y)
print()

print(np.add(x,y))
print()

print(x-y)
print(np.subtract(x,y))
print()

print(x/y)
print(np.divide(x,y))
print()

print(np.sqrt(x)) # root
print()

print(np.sum(x))
print(np.sum(x, axis=0)) # 행 기준
print(np.sum(x, axis=1)) # 열 기준

[[1. 2.]
 [3. 4.]]

[[5. 6.]
 [7. 8.]]

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[1.         1.41421356]
 [1.73205081 2.        ]]

10.0
[4. 6.]
[3. 7.]


In [ ]:
# print(x)
print()

print(x.T) #행 열 바꿔서 출력
print()

z = np.array(([[1,2],[3,4],[5,6]]))
print(z.shape)
print()

print(z)
print()

print(z.T)
print()

print(z.T.shape)
print()

In [17]:
x1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y1 = np.array([1,0,1])
y2 = x1 + y1
print(x1.shape)
print(y1.shape)
print(y2.shape)
print()
print(y2)

(4, 3)
(3,)
(4, 3)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
