In [7]:
import numpy as np
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
# 3 7 5
# 8 4 3
# 2 4 9

print(np.min(a)) #@@@@@@무슨차이???@@@@@@
print(np.amin(a)) 
print(np.amin(a,0)) #열 최소값
print(np.amin(a,1)) #행 최소값
print()

print(np.max(a)) # 최대값
print(np.amax(a))
print(np.amax(a, axis=0))
print(np.amax(a, axis=1))
print()

print(np.median(a)) # 중간값
print(np.median(a,axis = 0))
print(np.median(a,axis = 1))
print()

print(np.mean(a)) # 평균
print(np.mean(a,axis = 0))
print(np.mean(a,axis = 1))
print()

a = np.array([1,2,3,4])
print(np.std(a)) #표준편차?@@@@@@@@@@@@@@@@
print(np.var(a)) #분산?@@@@@@@@@@@


2
2
[2 4 3]
[3 3 2]

9
9
[8 7 9]
[7 8 9]

4.0
[3. 4. 5.]
[5. 4. 4.]

5.0
[4.33333333 5.         5.66666667]
[5. 5. 5.]

1.118033988749895
1.25
