In [20]:
import numpy as np
test = np.array([1,2,3])
print(test)
print()

test2 = np.array([[1,2,3],[4,5,6]])
print(test2)
print()

test3 = np.array([1,2,3,4,5], ndmin = 2)
print(test3)
print()

[1 2 3]

[[1 2 3]
 [4 5 6]]

[[1 2 3 4 5]]



In [13]:
print(test.shape)
print(test2.shape)
print(test3.shape)

(3,)
(2, 3)
(1, 5)


In [18]:
test4 = np.array([[1,2,3],[4,5,6]])
print(test4.shape)
print(test4)
print()

test5 = test4.reshape(3,2)
print(test5.shape)
print(test5)

(2, 3)
[[1 2 3]
 [4 5 6]]

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [22]:
test6 = np.arange(10)
print(test6)
print()

[0 1 2 3 4 5 6 7 8 9]



In [38]:
test8 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.amin(test8)) # 전체기준 min값
print(np.amin(test8,1)) # 행 기준 
print(np.amin(test8,0)) # 열 기준

print(np.amax(test8))
print(np.ptp(test8)) # min - max
print()


print(np.percentile(test8,50))
print(np.percentile(test8,50,1))
print(np.percentile(test8,50,0))

1
[1 4 7]
[1 2 3]
9
8

5.0
[2. 5. 8.]
[4. 5. 6.]


In [41]:
print(np.median(test8))
print(np.mean(test8))
print(np.std(test8)) # 표준편차

5.0
5.0
2.581988897471611


In [44]:
data = [1,2,3,4]
print(np.mean(data))
#평균 = 2.5// 편차 [1.5, 0.5, 0.5, 1.5]
print(np.std(data))
# 표준편차 = 편차의 제곱의 평균의 루트값

2.5
1.118033988749895
